PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'PCONTROL'
  MODULE PCONTROL_INIT.
*&SPWIZARD: MODULE PCONTROL_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE PCONTROL_CHANGE_COL_ATTR.
  LOOP AT   G_PCONTROL_ITAB
       INTO G_PCONTROL_WA
       WITH CONTROL PCONTROL
       CURSOR PCONTROL-CURRENT_LINE.
*&SPWIZARD:   MODULE PCONTROL_CHANGE_FIELD_ATTR
    MODULE PCONTROL_MOVE.
  ENDLOOP.

  MODULE STATUS_0100.
  MODULE FILL_LISTBOX.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'PCONTROL'
  LOOP AT G_PCONTROL_ITAB.
    CHAIN.
      FIELD ZSCREEN_PRACTICE-MATERIAL_NUMBER.
      FIELD ZSCREEN_PRACTICE-MATERIAL_DESCRIPTION.
      FIELD ZSCREEN_PRACTICE-QUANTITY.
      FIELD ZSCREEN_PRACTICE-SHIFT_INDICATOR.
      FIELD ZSCREEN_PRACTICE-CREATION_DATE.
      FIELD ZSCREEN_PRACTICE-USER_NAME.
      FIELD ZSCREEN_PRACTICE-DELETION_INDICATOR.
      MODULE PCONTROL_MODIFY ON CHAIN-REQUEST.
    ENDCHAIN.
  ENDLOOP.
*&SPWIZARD: MODULE PCONTROL_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE PCONTROL_CHANGE_COL_ATTR.

  MODULE USER_COMMAND_0100.
